updated p_author test in prep for testthat changes:
Email from Hadley...

This is an automated email to let you know about the upcoming release
of testthat, which will be submitted to CRAN on April 4. To check for
potential problems, I ran `R CMD check` on your package pacman
(0.3.0).

I found: 1 error  | 0 warnings | 0 notes.

    checking tests ... ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      `output` does not match "Deepayan Sarkar <deepayan.sarkar@r-project.org>".
      Actual value: ""

      Error in username %||% getOption("github.user") %||%
stop("Unknown username.") :
        Unknown username.
      testthat results
================================================================
      OK: 57 SKIPPED: 0 FAILED: 2
      1. Failure: p_author works (@test-p_author.R#4)
      2. Failure: p_author works (@test-p_author.R#5)

      Error: testthat unit tests failed
      Execution halted

If I got an ERROR because I couldn't install your package (or one of
it's dependencies), my apologies. You'll need to run the checks
yourself (unfortunately I don't have the time to diagnose installation
failures).

Otherwise, please carefully look at the results, and let me know if
I've introduced a bug in teststhat. There are two common classes of
new failures caused by this version of testthat:

1. `expect_output()` no longer automatically prints the object. You'll need to
   explicitly `print()` if you want to check the output of a print method.

2. `expect_error()` now only compares against the actual error message,
   not the prefix, e.g. "Error in foo(): ". You might need to change you
   match message to take this into account.

I realise updating tests that used to work doesn't seem like the best
use of anyone's time, but I'm confident these changes will improve the
overall reliability and robustness of testthat (and you have a month
to make the changes).

If it doesn't look like a bug in testthat, please prepare an update
for CRAN. Ideally you'll tweak your package so it works with both the
released and development versions of testthat. Otherwise, be prepared
to submit your package to CRAN soon after I let you know that I've
submitted.

To get the development version of testthat so you can run the checks
yourself, you can run:

    # install.packages("devtools")
    devtools::install_github("hadley/testthat")

To see what's changed visit
<https://github.com/hadley/testthat/blob/master/NEWS.md>.

If you have any questions about this email, please feel free to
respond directly.